### ISSUE TITLE
Certificate validation errors introduced in 4.8.1

### ISSUE THREAD

**Issue by justinfalk** [ITfoxtec/ITfoxtec.Identity.Saml2#106]
Hi,

We use Azure AD and are seeing certificate validation errors upon upgrading to 4.8.1+.  

```
2022-04-01 01:41:54.532 [ERR] (44) unknown | AuthController | Microsoft.IdentityModel.Tokens.SecurityTokenValidationException: Invalid X509 certificate chain. Certificate name:'CN=Microsoft Azure Federated SSO Certificate' and thumbprint:'XXX'. Chain Status:'self signed certificate'..
   at ITfoxtec.Identity.Saml2.Util.Saml2CertificateValidator.ValidateChainTrust(X509Certificate2 certificate)
   at ITfoxtec.Identity.Saml2.Util.Saml2CertificateValidator.Validate(X509Certificate2 certificate)
   at ITfoxtec.Identity.Saml2.Saml2Request.ValidateXmlSignature(XmlElement xmlElement)
   at ITfoxtec.Identity.Saml2.Saml2Request.ValidateXmlSignature(SignatureValidation documentValidationResult)
   at ITfoxtec.Identity.Saml2.Saml2Request.Read(String xml, Boolean validateXmlSignature, Boolean detectReplayedTokens)
   at ITfoxtec.Identity.Saml2.Saml2Response.Read(String xml, Boolean validateXmlSignature, Boolean detectReplayedTokens)
   at ITfoxtec.Identity.Saml2.Saml2AuthnResponse.Read(String xml, Boolean validateXmlSignature, Boolean detectReplayedTokens)
   at ITfoxtec.Identity.Saml2.Saml2PostBinding.Read(HttpRequest request, Saml2Request saml2RequestResponse, String messageName, Boolean validateXmlSignature, Boolean detectReplayedTokens)
   at ITfoxtec.Identity.Saml2.Saml2PostBinding.UnbindInternal(HttpRequest request, Saml2Request saml2RequestResponse, String messageName)
   at ITfoxtec.Identity.Saml2.Saml2Binding`1.Unbind(HttpRequest request, Saml2Response saml2Response)
```

![Screen Shot 2022-03-31 at 10 46 29 PM](https://user-images.githubusercontent.com/16879499/161185847-f71de294-f8de-410a-9c6c-29de4374ec26.png)

I don't think there is anything unusual about our configuration.  The message indicates that the certificate from microsoft is self-signed.  Is that causing the problem?

**Comment by Revsgaard** [comment]
Default settings is:
```
Saml2Configuration.CertificateValidationMode = X509CertificateValidationMode.ChainTrust;
Saml2Configuration.RevocationMode = X509RevocationMode.Online;
```
The default settings will not validate in your case.

Do it work for you? If you change to:
```
Saml2Configuration.CertificateValidationMode = X509CertificateValidationMode.None;
Saml2Configuration.RevocationMode = X509RevocationMode.NoCheck;
```
Can also be changed in config:
```
  "Saml2": {
    ...
    "CertificateValidationMode": "None", 
    "RevocationMode": "NoCheck"
  }
```

**Comment by justinfalk** [comment]
Thank you Anders!   That resolved my problem.

Could you confirm my summary of the changes?  Previously, the certificate validation was not being performed at all whereas in v4.8.1+ it is now done on every auth response.  In my case, the certificate that Azure is using is self-signed and thus failed validation.  Is that correct?

**Comment by Revsgaard** [comment]
Yes that is correct.
