### ISSUE TITLE
Failure to decrypt Encrypted key

### ISSUE THREAD

**Issue by IcoDeveloper** [ITfoxtec/ITfoxtec.Identity.Saml2#140]
I get an exception when trying to decrypt an encrypted assertion:
```
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
	<xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
	                    Id="_1ec9fa799683379dccd93aff503395ca"
	                    Type="http://www.w3.org/2001/04/xmlenc#Element">
		<xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes256-gcm"/>
		<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<xenc:EncryptedKey Id="_06bfcb49c962f9d4ea3b2d0bc5da7337">
				<xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep">
					<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
					<xenc11:MGF xmlns:xenc11="http://www.w3.org/2009/xmlenc11#"
					            Algorithm="http://www.w3.org/2009/xmlenc11#mgf1sha256"/>
				</xenc:EncryptionMethod>
				<xenc:CipherData>
					<xenc:CipherValue>xxxxxx</xenc:CipherValue>
				</xenc:CipherData>
			</xenc:EncryptedKey>
		</ds:KeyInfo>
		<xenc:CipherData>
			<xenc:CipherValue>yyyyyyyyy</xenc:CipherValue>
		</xenc:CipherData>
	</xenc:EncryptedData>
</saml2:EncryptedAssertion>
```
Stacktrace:
```
at System.Security.Cryptography.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, ReadOnlySpan`1 input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, Boolean encrypt)
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, Boolean encrypt)
   at System.Security.Cryptography.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)
   at System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbData)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptKey(Byte[] keyData, RSA rsa, Boolean useOAEP)
   at ITfoxtec.Identity.Saml2.Cryptography.Saml2EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey) in C:\git\github\ITfoxtec.Identity.Saml2\src\ITfoxtec.Identity.Saml2\Cryptography\Saml2EncryptedXml.cs:line 58
```
To me it looks like the issue is missing support for the used algorithms in System.Security.Cryptography.Xml.EncryptedXml? 
just changing the useOAEP flag in Saml2EncryptedXml.DecryptEncryptedKey doesn't improve things.
Any pointers greatly appreciated.

**Comment by Revsgaard** [comment]
It is probably encrypted with a method not supported by .NET. You probably need to set the required encryption method in the metadata handed over to the IdP. The wanted encryption method is added with `entityDescriptor.SPSsoDescriptor.SetDefaultEncryptionMethods();` see https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/master/test/TestWebAppCoreNemLogin3Sp/Controllers/MetadataController.cs#LL55C13-L55C76

**Comment by IcoDeveloper** [comment]
I've just added a pull request that addresses the issue (xmlenc11#rsa-oaep with separate DigestMethod) #143

**Comment by Revsgaard** [comment]
Closed, continued in the pull request.
