### ISSUE TITLE
Unbinding response with canonicalization method with comments results in invalid signature

### ISSUE THREAD

**Issue by appspace-adrian-tan** [ITfoxtec/ITfoxtec.Identity.Saml2#42]
Hi,

When unbinding a valid signed SAML Response with the canonicalization method `http://www.w3.org/2001/10/xml-exc-c14n#WithComments`:

```
<samlp:Response
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_8e8dc5f69a98cc4c1ff3427e5ce34606fd672f91e6" Version="2.0" IssueInstant="2014-07-17T01:01:48Z" Destination="http://sp.example.com/demo1/index.php?acs" InResponseTo="ONELOGIN_4fee3b046395c4e751011e97f8900b5273d56685">
    <saml:Issuer>http://idp.example.com/metadata.php</saml:Issuer>
    <Signature
        xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
            <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments" />
            <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <Reference URI="#_8e8dc5f69a98cc4c1ff3427e5ce34606fd672f91e6">
                <Transforms>
                    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments" />
                </Transforms>
                <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <DigestValue>VrztqVTjmfENj/VkwUEpVEl9R5UhS7xEL1p7I/nXbpo=</DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>FR4fISV9sYhOJ3475amBkW1WapUhkmKraVrigXQPXgKCuvhGhew34bzV33CxBDMEfNtfg5CIFeVQ0OJybqlmWJvjRKRoUcev9zhc5IwTWhmVF8r9bw7ymwKo0Uj6Vqji3WeMdaHdD9fB/MGJ6YwCn0i0g8Lisy6vqyBx1Y0cDr0+sdupqokDOe0aJ6OVsH4tty05F+98GoRbF7UXYIMyoVwRfp5vDKdoitEEOE+QIJmZrAt9evdLKxslrrroTUlJyxOX2zeovzq4JPDDvZUFYluYrz4UPxV/Ai+rJCcKNmQCWs6Zd0poWaZWB0LvwrXUjcSnSMVY+Q0b6GimFfB3tA==</SignatureValue>
        <KeyInfo>
            <X509Data>
                <X509Certificate>MIIDKjCCAhICCQCrM73GThlsczANBgkqhkiG9w0BAQUFADBOMQswCQYDVQQGEwJESzEQMA4GA1UEBwwHRGVubWFyazERMA8GA1UECgwISVRmb3h0ZWMxGjAYBgNVBAMMEXJvb3QuaXRmb3h0ZWMuY29tMB4XDTE2MDYxNjA3MzM1MFoXDTI2MDYxNDA3MzM1MFowYDELMAkGA1UEBhMCREsxEDAOBgNVBAcMB0Rlbm1hcmsxETAPBgNVBAoMCElUZm94dGVjMSwwKgYDVQQDDCNpdGZveHRlYy5pZGVudGl0eS5zYW1sMi50ZXN0aWRwY29yZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ8Ul5qUBZLLuHE9KN1bBvbHoFzHNm2sWQiZuR8CDaxinL4qFeeYOm7hKk0InDNsrwYJH0tmozSngwTR4MH5vibWxsFH2Izr7s18Wi7cM72BOi8FxR4odZ5qvrZfezoxRlSD8fPSGR92iALhuHRhczQ4BbqG6ig2MaUWxI1LptdaVKhCPJjhJLmTex0A9JEZunYwQC2HgZS59SRFwwOS98D7/bBPqMaeieTULrQCmPDyLsrozAE5e2Dc4tx/r9BeevQCCL7nl3yTc3bZ3/Dpp8odeOATeVtlp2V4iq0gim57dt6z4skXitiNx3OuIA/ghvcNcH/4yMudtXQlSZ+ONS8CAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAqw9aJgjSTTcB7By5EGFD/4dKeDDAv21pVu3blih+AQdiTntNevY/MQ/CJnRGvm/5knwCegeB9d5Ksg3ASVDkOJXPhrG/23kur1b0L4yk2m22B8RQz64G2VjuzVL/PPi0sJucIK1Mt6XviTKpIeT6KPJDj59G9N0ip2MqfvR/lgVUHqIzvPBo9k8rF5ndIVELr/khyH1dXbxsq5kDqAv8CJaOmFKVhRcp9KBxKG1RkcTnVl6m4CObVvC/+OwJ29L6eZwf/N7ZzpUUxw5XtvxiJWlh4zmVzPNupmnd7IE+5aQ/Gpqh8ZQsPu5mjQiRRr0w0h20RhloETWlLINBSPArTQ==</X509Certificate>
            </X509Data>
        </KeyInfo>
    </Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_d71a3a8e9fcc45c9e9d248ef7049393fc8f04e5f75" Version="2.0" IssueInstant="2014-07-17T01:01:48Z">
        <saml:Issuer>http://idp.example.com/metadata.php</saml:Issuer>
        <saml:Subject>
            <saml:NameID SPNameQualifier="http://sp.example.com/demo1/metadata.php" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_ce3d2948b4cf20146dee0a0b3dd6f69b6cf86f62d7</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData NotOnOrAfter="2024-01-18T06:21:48Z" Recipient="http://sp.example.com/demo1/index.php?acs" InResponseTo="ONELOGIN_4fee3b046395c4e751011e97f8900b5273d56685" />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2014-07-17T01:01:18Z" NotOnOrAfter="2024-01-18T06:21:48Z">
            <saml:AudienceRestriction>
                <saml:Audience>http://sp.example.com/demo1/metadata.php</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2014-07-17T01:01:48Z" SessionNotOnOrAfter="2024-07-17T09:01:48Z" SessionIndex="_be9967abd904ddcae3c0eb4189adbe3f71e327cf93">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xsi:type="xs:string">test</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xsi:type="xs:string">test@example.com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xsi:type="xs:string">users</saml:AttributeValue>
                <saml:AttributeValue xsi:type="xs:string">examplerole1</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>
```

I get the error below:
```
ITfoxtec.Identity.Saml2.Cryptography.InvalidSignatureException
  HResult=0x80131500
  Message=Signature is invalid.
  Source=ITfoxtec.Identity.Saml2
  StackTrace:
   at ITfoxtec.Identity.Saml2.Saml2Request.ValidateXmlSignature(SignatureValidation documentValidationResult)
   at ITfoxtec.Identity.Saml2.Saml2Request.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2Response.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2AuthnResponse.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2PostBinding.Read(HttpRequest request, Saml2Request saml2RequestResponse, String messageName, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2PostBinding.UnbindInternal(HttpRequest request, Saml2Request saml2RequestResponse, String messageName)
   at ITfoxtec.Identity.Saml2.Saml2Binding`1.Unbind(HttpRequest request, Saml2Response saml2Response)
```

**Comment by Revsgaard** [comment]
Hi, 

Thank you for your contribution and pull request.

I have build you pull request into the SAML 2.0 component with configuration. Please review the code in the branch before I commit:
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/pr/43-support-validation-of-xml-signed-with-xml-exc-c14n-withcomments-canon

Regards, Andes

**Comment by appspace-adrian-tan** [comment]
I'm glad i could help. The pull request looks good with the added configuration.
Thanks!

**Comment by Revsgaard** [comment]
I have released a beta version including the change https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.0.6-beta1. Please test and let me know if it works.
