### ISSUE TITLE
OIO SAML 3 support - error decrypting

### ISSUE THREAD

**Issue by Krisser50** [ITfoxtec/ITfoxtec.Identity.Saml2#80]
Hi here.

Is it possible to get support for NemLog-In 3 with OIO SAML 3?

I have tried to use the current version, and I get the following error:
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The parameter is incorrect.'

Stacktrace:
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, ReadOnlySpan`1 input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, Boolean encrypt)
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, Boolean encrypt)
   at System.Security.Cryptography.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)
   at System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbIn)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptKey(Byte[] keyData, RSA rsa, Boolean useOAEP)
   at ITfoxtec.Identity.Saml2.Cryptography.Saml2EncryptedXml.DecryptEncryptedKey(EncryptedKey encryptedKey)
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at ITfoxtec.Identity.Saml2.Saml2AuthnResponse.DecryptMessage()
   at ITfoxtec.Identity.Saml2.Saml2Request.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2Response.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2AuthnResponse.Read(String xml, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2PostBinding.Read(HttpRequest request, Saml2Request saml2RequestResponse, String messageName, Boolean validateXmlSignature)
   at ITfoxtec.Identity.Saml2.Saml2Binding`1.ReadSamlResponse(HttpRequest request, Saml2Response saml2Response)

I have messed around with both the metadata and swapping certificates, but nothing works.

I hope you can help!

Best regards

Christian H. Karleby.

**Comment by Revsgaard** [comment]
Hi,

I'm in doubt as to what caused that error. As of my knowledge the component should support OIOSAML 3. I'm not aware that there should be any changes from OIOSAML 2 to OIOSAML 3 regarding signing.

Regards, Anders

**Comment by Revsgaard** [comment]
I'm afraid that I cannot solve the problem based on the information and currently I do not have access to the NemLog-In 3 test environment. I'll connect customers in the fall of 2021 and at that time look into this problem.

**Comment by gpikmddk** [comment]
Based on this [link](https://www.digitaliser.dk/news/6072243), NemLogin3 will by default encrypt with algorithms, that .NET cannot handle. They describe a way of forcing other algorithms. It has to be done in metadata. Based on the link it should be something like that:
<md:KeyDescriptor use=”encryption”>
  <ds: KeyInfo>…</ds: KeyInfo>
  <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" />
  <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p" />
</md:KeyDescriptor>
